### ISSUE TITLE
Problema na apresentação de "Quality Assessment" - Issue #180 

### ISSUE THREAD

**Issue by auri-gabriel** [auri-gabriel/Thoth#2]
**Describe the bug**
Ao aplicar filtros em "Quality Assessment" pode ser que não exista nenhum título, porém a mensagem de que há uma linha selecionada permanece.

**To Reproduce**
1. Acesse a aba "Quality Assessment"
2. Aplique um filtro que não corresponde a nenhum título
3. Verifique que a mensagem de que há uma linha selecionada permanece

**Expected behavior**
A mensagem de que há uma linha selecionada deve desaparecer caso nenhum título seja encontrado após aplicar filtros.

**Screenshots**
![Screenshot_20191117_220012](https://user-images.githubusercontent.com/50750176/69017470-04dbc200-0986-11ea-841c-2bdd45ee0867.png)

**Additional context**
N/A

---
Este problema é uma continuação do issue #180.

**Comment by joaoemiliovilla** [comment]
Depois de analisarmos essa issue, chegamos a conclusão de que ela não é considerada um erro.
Pois quando selecionamos alguma linha da tabela (ela fica azul), e vamos filtrar algo, que resulta em nenhuma pesquisa, a mensagem de que "ha 1 row selecionada" continua, justamente por que quando tiramos o filtro, a nossa row continua selecionada, independente se ela encontrou algo no filtro ou não.
